- name: CentOS 7 VM を用意する
  hosts: targets
  gather_facts: false
  tasks:
    - name: ESXi 上に VM を作成する
      local_action:
        module: vsphere_guest
        vcenter_hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_pass }}"
        guest: "{{ vm_name }}"
        state: powered_on
        validate_certs: false
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd:  yes
        vm_disk:
          disk1:
            size_gb: 20
            type: thin
            datastore: "{{ vm_datastore }}"
            folder: disk1.vmdk
        vm_nic:
          nic1:
            type: vmxnet3
            network: bergenholm
            network_type: standard
        vm_hardware:
          memory_mb: 2048
          num_cpus: 2
          osid: centos64Guest
          scsi: paravirtual
        esxi:
          datacenter: ha-datacenter
          hostname: eval3
    - name: ESXi 上の VM の情報を取得する
      local_action:
        module: vsphere_guest
        vcenter_hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_pass }}"
        guest: "{{ vm_name }}"
        vmware_guest_facts: true
        validate_certs: false
        esxi:
          datacenter: ha-datacenter
          hostname: eval3
      register: newvm
    - name: Bergenholm 上に新しい VM の設定を登録する
      local_action:
        module: bergenholm_host
        uuid: "{{ newvm.ansible_facts.hw_product_uuid }}"
        params:
          groups:
            - centos7
            - centos.amd64
          hostname: "{{ vm_name }}"
          ipaddr: "{{ vm_ipaddr }}"
          netif: ens192
        state: present
      notify:
        - VM を再起動して OS インストールを開始する
  handlers:
    - name: VM を再起動して OS インストールを開始する
      local_action:
        module: vsphere_guest
        vcenter_hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_pass }}"
        guest: "{{ vm_name }}"
        state: restarted
        validate_certs: false

- name: OS インストール後の確認を行う
  hosts: targets
  gather_facts: false
  tasks:
    - name: OS インストール完了待ち
      wait_for_connection:
        sleep: 10
        timeout: 3600
    - name: Facts を取得する
      setup:
    - name: ディストリビューション情報を表示する
      debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ansible_distribution_release}})" 
