- name: VM を削除する
  hosts: targets
  gather_facts: false
  tasks:
    - name: ESXi 上の VM 情報を取得する
      local_action:
        module: vsphere_guest
        vcenter_hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_pass }}"
        guest: "{{ vm_name }}"
        vmware_guest_facts: true
        validate_certs: false
        esxi:
          datacenter: ha-datacenter
          hostname: eval3
      register: newvm
      ignore_errors: true
    - name: ESXi 上の VM を削除する
      local_action:
        module: vsphere_guest
        vcenter_hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_pass }}"
        guest: "{{ vm_name }}"
        state: absent
        force: true
        validate_certs: false
        esxi:
          datacenter: ha-datacenter
          hostname: eval3
    - name: Bergenholm 上の VM の設定を削除する
      local_action:
        module: bergenholm_host
        uuid: "{{ newvm.ansible_facts.hw_product_uuid }}"
        state: absent
      when: newvm | success
